connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://iceberg-rest:8181
iceberg.rest-catalog.warehouse=s3://warehouse/
iceberg.rest-catalog.vended-credentials-enabled=true
iceberg.security=ALLOW_ALL
iceberg.file-format=PARQUET
iceberg.compression-codec=ZSTD
iceberg.max-commit-retry=10
iceberg.target-max-file-size=128MB
iceberg.metadata.parallelism=8
iceberg.expire-snapshots.min-retention=7d
iceberg.remove-orphan-files.min-retention=7d

fs.s3.enabled=true
s3.endpoint=http://minio:9000
s3.region=${ENV:AWS_REGION}
s3.aws-access-key=${ENV:AWS_ACCESS_KEY_ID}
s3.aws-secret-key=${ENV:AWS_SECRET_ACCESS_KEY}
s3.path-style-access=true

iceberg.register-table-procedure.enabled=false
iceberg.add-files-procedure.enabled=true
iceberg.allowed-extra-properties=*


